# Not considered useful hints
- ignore:
    name: "Use camelCase"
    within:
    - System.Terminal
- ignore:
    name: "Use fewer imports"
    within:
    - Pantry.Types
- ignore:
    name: "Functor law"
    within:
    - Pantry.Types
